//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_race_v3
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    
    public partial class tblRace
    {
        public int RaceID { get; set; }
        public string RaceLocation { get; set; }
        public int RaceLengthMiles { get; set; }
        public decimal RaceWinnings { get; set; }
        public int Winner { get; set; }
    



        public virtual tblRallyRacer tblRallyRacer { get; set; }
    }

    public class tblRaceDBContext : DbContext
    {
        public DbSet<tblRace> tblRace { get; set; }

        public System.Data.Entity.DbSet<mvc_race_v3.tblRallyRacer> tblRallyRacers { get; set; }
    }


}
